[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "lcspec"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pyyaml",
    "requests",
    "ipykernel",
    "seaborn",
    "libtmux",
    "ipywidgets",
    "nbformat>=4.2.0",
    "numpy",
    "pandas",
    "plotly",
    "pyarrow",
    "tqdm",
    "datasets",
    "locust",
    "scipy",
    "psycopg2-binary",
    "python-dotenv",
    "matplotlib",
    "transformers",
    "ray",
    "torch",
    "tensorboard",
]

[project.optional-dependencies]
dev = ["pre-commit", "black", "isort", "ruff"]

[tool.setuptools.packages.find]
include = ["perfomance*"]

[tool.black]
target-version = ["py312"]

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.prettier]
semi = false
singleQuote = true
tabWidth = 2

[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I"]
