single_setup:
  server_args:
    {
      "model": "RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8",
      "enable_prefix_caching": False,
      "disable_log_stats": False,
      "speculative_config": {
        "model": "/workspace/workflow/LCSpec/output/finetune_yarn/checkpoints/19",
        "method": "eagle3",
        "num_speculative_tokens": 3,
      }
    }
