single_setup:
  server_args:
    {
      "model": "RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8",
      "enable_prefix_caching": False,
      "disable_log_stats": False,
      "speculative_config": {
        "model": "RedCaesar/partial_08_4",
        "method": "eagle3_lc",
        "num_speculative_tokens": 3,
      }
    }
