single_setup:
  server_args:
    {
      "model": "/home/models/meta-llama/Llama-3.1-8B-Instruct/",
      "enable_prefix_caching": False,
      "disable_log_stats": False,
      "speculative_config": {
        "model": "/home/models/yuhuili/EAGLE3-LLaMA3.1-Instruct-8B",
        "method": "eagle3",
        "num_speculative_tokens": 4,
      }
    }


few_setups: [
  {"server_args":
    {
      "model": "/home/models/meta-llama/Llama-3.1-8B-Instruct/",
      "tensor_parallel_size": 1,
      "enable_prefix_caching": False,
    }
  },
  {"server_args":
    {
      "model": "/home/models/meta-llama/Llama-3.1-8B-Instruct/",
      "tensor_parallel_size": 1,
      "enable_prefix_caching": False,
      "disable_log_stats": False,
      "speculative_config": {
        "model": "yuhuili/EAGLE3-LLaMA3.1-Instruct-8B",
        "method": "eagle3",
        "num_speculative_tokens": 4,
      }
    }
  },
]
