setups: [
  {
    "load_test": {
      "users": "1",
      "run-time": "60s",
      "dataset-type": "summary",
      "output-tokens-distribution": "\"const(250)\"",
      "run-id": "sd_new_yarn",
    },
    "vllm": {
      "server_args": {
        "model": "RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8",
        "no-enable-prefix-caching": "",
        "speculative_config": {
          "model": "/workspace/workflow/LCSpec/output/finetune_yarn/checkpoints/19",
          "method": "eagle3",
          "num_speculative_tokens": 3,
        }
      },
      "env": {"VLLM_DISABLE_COMPILE_CACHE": "1"}
    }
  }
]