setups: [
  {
    "load_test": {
      "users": "1",
      "run-time": "60s",
      "input-tokens-distribution": "\"const(1024)\"",
      "dataset-type": "summary",
      "output-tokens-distribution": "\"const(250)\"",
      "run-id": "sd",
    },
    "vllm": {
      "server_args": {
        "model": "RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8",
        "no-enable-prefix-caching": "",
        "speculative_config": {
          "model": "RedCaesar/EAGLE3-LLaMA3.1-Instruct-8B",
          "method": "eagle3",
          "num_speculative_tokens": 1,
        }
      },
      "env": {}
    }
  },
  {
    "load_test": {
      "users": "1",
      "run-time": "60s",
      "input-tokens-distribution": "\"const(1024)\"",
      "dataset-type": "summary",
      "output-tokens-distribution": "\"const(250)\"",
      "run-id": "sd",
    },
    "vllm": {
      "server_args": {
        "model": "RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8",
        "no-enable-prefix-caching": "",
        "speculative_config": {
          "model": "RedCaesar/EAGLE3-LLaMA3.1-Instruct-8B",
          "method": "eagle3",
          "num_speculative_tokens": 2,
        }
      },
      "env": {}
    }
  },
  {
    "load_test": {
      "users": "1",
      "run-time": "60s",
      "input-tokens-distribution": "\"const(1024)\"",
      "dataset-type": "summary",
      "output-tokens-distribution": "\"const(250)\"",
      "run-id": "sd",
    },
    "vllm": {
      "server_args": {
        "model": "RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8",
        "no-enable-prefix-caching": "",
        "speculative_config": {
          "model": "RedCaesar/EAGLE3-LLaMA3.1-Instruct-8B",
          "method": "eagle3",
          "num_speculative_tokens": 3,
        }
      },
      "env": {}
    }
  },
  {
    "load_test": {
      "users": "1",
      "run-time": "60s",
      "input-tokens-distribution": "\"const(1024)\"",
      "dataset-type": "summary",
      "output-tokens-distribution": "\"const(250)\"",
      "run-id": "sd",
    },
    "vllm": {
      "server_args": {
        "model": "RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8",
        "no-enable-prefix-caching": "",
        "speculative_config": {
          "model": "RedCaesar/EAGLE3-LLaMA3.1-Instruct-8B",
          "method": "eagle3",
          "num_speculative_tokens": 4,
        }
      },
      "env": {}
    }
  }
]